version: '1.0'
services:
  web:
    image: "ghcr.io/or-homelab/shared-shopping-list:latest"
    ports:
      - "80:8080"
    environment:
      - PORT=8080
      - SESSION_SECRET=";w$jb`.j6#PDG&gvxpc-@&JyU)dtD;"
      - REQUIRE_PASSWORD_FOR_REGISTER=True
      - MONGODB_URL=mongodb://db/shopping-list
  db:
    image: "mongo"
    restart: "always"
    volumes:
      - databasedata:/data/db
    environment:
      MONGO_INITDB_DATABASE: shopping-list
volumes:
  databasedata:
    driver: local
    driver_opts:
      type: none
      device: ./appdata/databasedata
      o: bind